### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by Piotr45** [Piotr45/cmos-preprocessor#66]
DevOps:
- [ ] Docker container
- [ ] Hydra config files
- [ ] CI/CD
- [ ] Unit and Integration tests

New Features:
- [ ] Add PyTorch and Lightning
- [ ] Add MLflow for training tracking
- [ ] Add export scripts (export preprocessor to MLflow)
- [ ] Reimplement preprocessor parser
- [ ] Implement new generic class for datasets

Research:
- [ ] Find new problem (and dataset)
- [ ] Implement smart pruning
